<a href="https://colab.research.google.com/github/LuizSerapiao/Atividade1-CPA/blob/main/Atividade_1_Pontos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EFC1 GCC253 - Complexidade e Projeto de Algoritmos - 5 pontos.


> **Prof.: Douglas H. S. Abreu**


**Aluno**: Luiz Felipe Baptista Serapião

**Matricula**: 201620440

**Turma**: 10A

Link do repositório GitHub: https://github.com/LuizSerapiao/Atividade1-CPA/blob/fa14ce440ecea2a91f9309493018f7ebe148d4d5/README.md

● O trabalho deve ser feito em grupos de no máximo 4 componentes (Apenas um deve enviar a atividade no Campus Virtual)

● Trabalhos entregues após a data limite não serão aceitos

● Data limite de entrega: 20 de Novembro de 2022 : 23h55m

● Enviar o trabalho para o campus virtual, do seguinte modo: link do repositório GitHub com acesso ao Notebook.

● O trabalho deve ser desenvolvido no modelo Notebook utilizando preferencialmente a linguagem Python

# Importações e Variáveis globais

In [68]:
import numpy as np

global_1=0
Array1 = [7, 1, 7, 5, 8, 1, 8, 9, 5, 4, 54]
Array2 = [1000, 40, 23, 57, 46, 58, 66, 99 ,45 ,555]
Array3 = [44, 111, 243, 554, 28, 331, 418, 649, 785, 4, 54354]
arrays = []
arrays.append(Array1)
arrays.append(Array2)
arrays.append(Array3)

# Funções de Ordenação

> Utilize este espaço para definir as funções de ordenação.



##  Insertion Sort


In [ ]:
def insertionSort(A):
  j=2
  for j in range(len(A)):
    chave = A[j]
    i = j-1
    while i>=0 and A[i]>=chave:
      A[i+1] = A[i]
      i = i-1
    A[i+1] = chave
  return A

##  Merge Sort


In [ ]:
def mergeSort(A):
    if len(A)>1:
        mid = len(A)//2
        lefthalf = A[:mid]
        righthalf = A[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)

        i=0
        j=0
        k=0
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i] < righthalf[j]:
                A[k]=lefthalf[i]
                i=i+1
            else:
                A[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            A[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            A[k]=righthalf[j]
            j=j+1
            k=k+1
    return A

##  Selection Sort


In [ ]:
def selectionSort(A):
  length = len(A)
  for item in range(length):
    minimum = item

    for i in range(item + 1, length):
      if A[i] < A[minimum]:
        minimum = i

    (A[item], A[minimum]) = (A[minimum], A[item])
  return A

##  Bubble Sort


In [ ]:
def bubbleSort(A):
  n = len(A)
  swapped = False
  
  for i in range(n-1):
      
      for j in range(0, n-i-1):

          
          if A[j] > A[j + 1]:
              swapped = True
              A[j], A[j + 1] = A[j + 1], A[j]
        
      if not swapped:
          return A
  return A

## Heap Sort

In [ ]:
def heapify(arr, n, i):
  # Find largest among root and children
  largest = i
  l = 2 * i + 1
  r = 2 * i + 2

  if l < n and arr[i] < arr[l]:
      largest = l

  if r < n and arr[largest] < arr[r]:
      largest = r

  # If root is not largest, swap with largest and continue heapifying
  if largest != i:
      arr[i], arr[largest] = arr[largest], arr[i]
      heapify(arr, n, largest)

def heapSort(arr):
  n = len(arr)
  
  # Build max heap
  for i in range(n//2, -1, -1):
      heapify(arr, n, i)

  for i in range(n-1, 0, -1):
      # Swap
      arr[i], arr[0] = arr[0], arr[i]

      # Heapify root element
      heapify(arr, i, 0)
  return arr

## Quick Sort com pivo sendo o ultimo elemento do arranjo

> pivo = *A[A-comprimento]*

In [73]:
def quickSort(alist):
   quickSortHelper(alist,0,len(alist)-1)
   pivo = alist[len(alist)-1]-len(alist)
   alist[len(alist)-1] = pivo
   return alist

def quickSortHelper(alist,first,last):
   if first<last:

       splitpoint = partition(alist,first,last)

       quickSortHelper(alist,first,splitpoint-1)
       quickSortHelper(alist,splitpoint+1,last)


def partition(alist,first,last):
   pivotvalue = alist[first]

   leftmark = first+1
   rightmark = last

   done = False
   while not done:

       while leftmark <= rightmark and alist[leftmark] <= pivotvalue:
           leftmark = leftmark + 1

       while alist[rightmark] >= pivotvalue and rightmark >= leftmark:
           rightmark = rightmark -1

       if rightmark < leftmark:
           done = True
       else:
           temp = alist[leftmark]
           alist[leftmark] = alist[rightmark]
           alist[rightmark] = temp

   temp = alist[first]
   alist[first] = alist[rightmark]
   alist[rightmark] = temp


   return rightmark

# Questões



1.   Escolha pelo menos 3 arranjos. Ex: ***A[5,...,1000,...,100]*** e mostre o funcionamento dos Algoritmos realizando a ordenação.





In [72]:
print("Arrays originais:")
for array in arrays:
  print(array)

print("InsertionSort:")
for array in arrays:
  print(insertionSort(np.array(array)))

print("MergeSort:")
for array in arrays:
  print(mergeSort(np.array(array)))

print("SelectionSort:")
for array in arrays:
  print(selectionSort(np.array(array)))

print("BubbleSort:")
for array in arrays:
  print(bubbleSort(np.array(array)))

print("HeapSort:")
for array in arrays:
  print(heapSort(np.array(array)))

print("QuickSort:")
for array in arrays:
  print(quickSort(np.array(array)))

Arrays originais:
[7, 1, 7, 5, 8, 1, 8, 9, 5, 4, 54]
[1000, 40, 23, 57, 46, 58, 66, 99, 45, 555]
[44, 111, 243, 554, 28, 331, 418, 649, 785, 4, 54354]
InsertionSort:
[ 1  1  4  5  5  7  7  8  8  9 54]
[  23   40   45   46   57   58   66   99  555 1000]
[    4    28    44   111   243   331   418   554   649   785 54354]
MergeSort:
[ 1  1  1  1  1  1  4  4  4  4 54]
[ 23  23  23  45  45  45  45  45  45 555]
[    4     4     4     4     4     4     4     4     4     4 54354]
SelectionSort:
[ 1  1  4  5  5  7  7  8  8  9 54]
[  23   40   45   46   57   58   66   99  555 1000]
[    4    28    44   111   243   331   418   554   649   785 54354]
BubbleSort:
[ 1  1  4  5  5  7  7  8  8  9 54]
[  23   40   45   46   57   58   66   99  555 1000]
[    4    28    44   111   243   331   418   554   649   785 54354]
HeapSort:
[ 1  1  4  5  5  7  7  8  8  9 54]
[  23   40   45   46   57   58   66   99  555 1000]
[    4    28    44   111   243   331   418   554   649   785 54354]
QuickSort:
43
[ 1  1 